version: '3.9'
services:
  opentrashmail:
    image: 'hascheksolutions/opentrashmail:1'
    volumes:
      - './data:/var/www/opentrashmail/data'
      - './logs:/var/www/opentrashmail/logs'
    environment:
      - URL=$URL
      - DOMAINS=$DOMAINS
      - DATEFORMAT=$DATEFORMAT
      - SKIP_FILEPERMISSIONS=$SKIP_FILEPERMISSIONS
      - DISCARD_UNKNOWN=$DISCARD_UNKNOWN
      - ADMIN_ENABLED=$ADMIN_ENABLED
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
      - PASSWORD=$PASSWORD
      - ALLOWED_IPS=$ALLOWED_IPS
      - ATTACHMENTS_MAX_SIZE=$ATTACHMENTS_MAX_SIZE
      - MAILPORT_TLS=$MAILPORT_TLS
      - TLS_CERTIFICATE=$TLS_CERTIFICATE
      - TLS_PRIVATE_KEY=$TLS_PRIVATE_KEY
      - WEBHOOK_URL=$WEBHOOK_URL

    ports:
      - '25:25'
